CREATE DATABASE IF NOT EXISTS FINSIGHT;

CREATE SCHEMA IF NOT EXISTS FINSIGHT.RAW;
CREATE SCHEMA IF NOT EXISTS FINSIGHT.STAGING;
CREATE SCHEMA IF NOT EXISTS FINSIGHT.CORE;
CREATE SCHEMA IF NOT EXISTS FINSIGHT.MART;

SELECT
    CURRENT_DATABASE() AS database_name,
    CURRENT_SCHEMA() AS schema_name;